name: CI/CD workflow

on:
  # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

  # Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write


jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-python@v5
            with:
              python-version: '3.13'
              cache: 'pipenv' # caching pip dependencies
          - run: python --version
          - run: python -m pip install --upgrade pip
          - run: pip install pipenv
          - run: pipenv install
          - run: pipenv run pip list
          - run: mkdir output
          - run: pipenv run python main.py
          - run: ls -al output/


  # Deployment job
    deploy:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        needs: build
        steps:
          - name: Upload static files as artifact
            uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
            with:
              path: output/
          - name: Deploy to GitHub Pages
            id: deployment
            uses: actions/deploy-pages@v4
