name: CI/CD workflow

on:
  # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v5
          with:
            python-version: '3.13'
            cache: 'pipenv' # caching pip dependencies
        - run: python3 --version
        - run: python3 -m pip install --upgrade pip
        - run: pip3 install pipenv
        - run: pipenv install
        - run: pipenv run pip3 list
        - run: pip3 list
        - run: python3 main.py
        - name: Upload static files as artifact
          uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
          with:
            path: output/


  # Deployment job
    deploy:
        environment:
            name: github-pages
            url: "caferequerido.github.io"
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
